(()=>{
const root=document.getElementById('localPage'),city=document.body.dataset.city,s=document.body.dataset.service;
if(!root||!city||!s)return;
const cfg={
'znishchennia-tarhaniv':{title:'Знищення тарганів',type:'Дезінсекція',img:'cockroach.svg',lead:'Професійна обробка квартир, будинків, магазинів, кафе та інших об’єктів від тарганів.'},
'znishchennia-klopiv':{title:'Знищення клопів',type:'Дезінсекція',img:'bedbug.svg',lead:'Комплексна обробка спальних зон, меблів, щілин та інших місць укриття постільних клопів.'},
'deratyzatsiia':{title:'Дератизація',type:'Миші та щури',img:'rodents.svg',lead:'Пошук шляхів проникнення, засоби контролю, моніторинг і профілактика повторної появи гризунів.'},
'pest-control':{title:'Pest Control для бізнесу',type:'HACCP / моніторинг',img:'disinfection.svg',lead:'Системний контроль шкідників для магазинів, HoReCa, складів, агро- та виробничих підприємств.'}};
const x=cfg[s];if(!x)return;
const phone='099 272 78 29';
root.innerHTML=`<div class="topbar"><div class="container"><div>📍 ${city} та область</div><div class="right"><span>🇺🇦 Працюємо по Україні</span><span>Щодня 8:00–20:00</span></div></div></div>
<header class="header"><div class="container nav"><a class="brand" href="index.html"><div class="target"><span class="rat">🐀</span></div><div class="brand-text"><strong><b>STOP</b>ШКІДНИК</strong><span>ПРОФЕСІЙНИЙ ПЕСТ-КОНТРОЛЬ</span></div></a><nav class="menu"><a href="index.html">Головна</a><a href="private.html">Приватним</a><a href="business.html">Для бізнесу</a><a href="contacts.html">Контакти</a></nav><button class="mobile-toggle" type="button" aria-label="Відкрити меню">☰</button><div class="nav-cta"><a class="phone" href="tel:+380992727829">${phone}</a><a class="btn btn-yellow" href="contacts.html">Консультація</a></div></div></header>
<div class="mobile-menu" id="mobileMenu"><a href="index.html">Головна</a><a href="private.html">Приватним</a><a href="business.html">Для бізнесу</a><a href="contacts.html">Контакти</a></div>
<main><section class="page-hero"><div class="container"><div class="eyebrow" style="color:var(--yellow)">${x.type} • ${city}</div><h1>${x.title.toUpperCase()} У ${city.toUpperCase()}</h1><p>${x.lead}</p><div class="hero-actions"><a class="btn btn-yellow" href="tel:+380992727829">Зателефонувати</a><a class="btn btn-outline" style="background:transparent;color:white;border-color:white" href="contacts.html">Замовити консультацію</a></div><div class="hero-pest-visual"><img src="assets/pests/${x.img}" alt="${x.title} у ${city}"><span>${x.title}</span></div></div></section>
<section class="section"><div class="container seo-visual"><div class="seo-visual-image"><img src="assets/pests/${x.img}" alt="${x.title} у ${city}" loading="lazy"></div><div><div class="eyebrow">Локальний виїзд</div><h2>${x.title} у ${city}</h2><p>${x.lead}</p><p>Метод, кількість візитів і вартість визначаємо після уточнення типу об’єкта, масштабу проблеми та умов на місці.</p></div></div></section>
<section class="section soft"><div class="container"><div class="section-head"><div><div class="eyebrow">Процес</div><h2>Як проходять роботи</h2></div></div><div class="steps"><div class="step"><b>1</b><h3>Консультація</h3><p>Уточнюємо проблему та об’єкт.</p></div><div class="step"><b>2</b><h3>Підготовка</h3><p>Надаємо рекомендації до виїзду.</p></div><div class="step"><b>3</b><h3>Обробка</h3><p>Проводимо роботи підібраним методом.</p></div><div class="step"><b>4</b><h3>Контроль</h3><p>Рекомендації та профілактика.</p></div></div></div></section>
<section class="section"><div class="container"><div class="grid split"><div class="card"><h3>Для приватних клієнтів</h3><p>Квартири, будинки, підвали, гаражі та господарські приміщення.</p></div><div class="card"><h3>Для бізнесу</h3><p>HoReCa, магазини, склади, виробництва та агропідприємства. Для корпоративних клієнтів — документування робіт.</p></div></div></div></section>
<section class="section soft"><div class="container"><div class="cta"><div class="cta-left"><h2>Потрібна допомога у ${city}?</h2><p>Телефонуйте — уточнимо ситуацію та запропонуємо формат робіт.</p></div><div class="cta-right"><strong style="font-size:28px">${phone}</strong><a class="btn btn-dark" href="contacts.html">Залишити звернення</a></div></div></div></section></main>
<footer class="footer"><div class="container"><div class="footer-grid"><div><a class="brand" href="index.html"><div class="target"><span class="rat">🐀</span></div><div class="brand-text"><strong><b>STOP</b>ШКІДНИК</strong><span>ПРОФЕСІЙНИЙ ПЕСТ-КОНТРОЛЬ</span></div></a><p>Професійний контроль шкідників для дому та бізнесу.</p></div><div><h4>Навігація</h4><a href="index.html">Головна</a><a href="private.html">Приватним</a><a href="business.html">Для бізнесу</a><a href="contacts.html">Контакти</a></div><div><h4>Контакти</h4><a href="tel:+380992727829">${phone}</a><a href="mailto:chernobay88@ukr.net">chernobay88@ukr.net</a></div></div><div class="copyright">© 2021–2026 STOPШКІДНИК.</div></div></footer>
<div class="floating-contact" aria-label="Швидкий зв’язок"><a class="float-btn float-mail" href="mailto:chernobay88@ukr.net">✉</a><a class="float-btn float-phone" href="tel:+380992727829">☎</a></div>`;
})();